spring:
  application:
    name: auth-service
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/spring
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: admin
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sal: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    database: mysql
    show-sql: true
  sql:
    init:
      mode: always
#      data-locations: classpath:sql/data.sql
      schema-Locations: classpath:sql/schema.sql

server:
  port: 8081